import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Would You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.png" />
      </Head>

      <Navbar />

      <main className="homepage-main">
        <div className="left">
          <h1>Entertain Your <span className="red">Discord</span> <span className="blue">Server</span></h1>
          <p>Utilize Would You to entertain your server.</p>
          <button className="wy-button primary">Invite</button>
        </div>
        <div className="right"></div>
      </main>
    </>
  );
}
